name: Build rbxlx-to-rojo

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry and build
        uses: Swatinem/rust-cache@v2

      - name: Build (all features)
        run: cargo build --locked --release --all-features

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: rbxlx-to-rojo-windows
          path: target/release/rbxlx-to-rojo.exe


  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry and build
        uses: Swatinem/rust-cache@v2

      - name: Build (all features)
        run: cargo build --locked --release --all-features

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: rbxlx-to-rojo-macos
          path: target/release/rbxlx-to-rojo